name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
        for config in [ subnet-remaining-ips.yaml fsx-filesystem-availability.yaml eks-limits.yaml ] ; do
          rm -rf build/
          rm -rf cdk.out/
          npm run prepareEnv
          npm run validate
        done
